defmodule OfferService.Auction.Request do
  use Ecto.Schema
  import Ecto.Changeset

  alias OfferService.Auction.Offer

  @type t :: %__MODULE__{}

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "requests" do
    field :client_id, :binary_id
    field :status, :string, default: "open"
    field :accepted_offer_id, :binary_id
    field :chat_thread_id, :string
    field :lock_version, :integer, default: 1

    has_many :offers, Offer

    timestamps(type: :utc_datetime_usec)
  end

  @doc """
  Changeset for the gateway request-bridge (`POST /api/v1/requests`).

  The gateway is the system-of-record for a delivery request; it forwards the
  request_id it already issued so offer-service can mirror the row before any
  offer is submitted against it (`Submit.lock_request/2` requires the row to
  exist). The `id` is therefore caller-supplied, not autogenerated.

  Only the columns the auction domain reads are accepted — `id`, `client_id`,
  and an optional lifecycle `status`. `accepted_offer_id`, `chat_thread_id`,
  and `lock_version` are owned exclusively by the accept saga and are never
  set through this path, so a re-mirror can never clobber an in-flight
  acceptance.
  """
  @spec upsert_changeset(map()) :: Ecto.Changeset.t()
  def upsert_changeset(attrs) do
    %__MODULE__{}
    |> cast(attrs, [:id, :client_id, :status])
    |> validate_required([:id, :client_id])
    |> validate_inclusion(:status, ~w(open accepted cancelled expired))
  end

  @spec accept_changeset(t(), %{accepted_offer_id: binary, chat_thread_id: binary | nil}) ::
          Ecto.Changeset.t()
  def accept_changeset(%__MODULE__{} = request, attrs) do
    request
    |> cast(attrs, [:accepted_offer_id, :chat_thread_id])
    |> put_change(:status, "accepted")
    |> validate_required([:accepted_offer_id])
    |> validate_inclusion(:status, ~w(open accepted cancelled expired))
    |> optimistic_lock(:lock_version)
  end
end
